name = "todo-preview-prod"
main = "src/index.js"
account_id = "3adac28a3b149802baa44f3eff150449"
compatibility_date = "2025-06-09"
workers_dev = true
type = "javascript"

[[kv_namespaces]]
binding = "TODOS"
id = "5ce424bd95d245208ad06f0692dce16f"

[env.dev]
name = "todo-preview-dev"

[[env.dev.kv_namespaces]]
binding = "TODOS"
id = "4a886cec6a3c4576af351690716576af"
